on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Workflow setup all good. Ready for next questions"
